//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_tb
    {
        public Company_tb()
        {
            this.ApplyJob_tb = new HashSet<ApplyJob_tb>();
            this.PostJob_tb = new HashSet<PostJob_tb>();
        }
    
        public int CID { get; set; }
        public string CNAME { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNo { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual ICollection<ApplyJob_tb> ApplyJob_tb { get; set; }
        public virtual ICollection<PostJob_tb> PostJob_tb { get; set; }
    }
}
