//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_tb
    {
        public int EID { get; set; }
        public Nullable<int> Job_seeker_ID { get; set; }
        public string CollageName { get; set; }
        public string Enrollment_Number { get; set; }
        public string Semester { get; set; }
        public string Education { get; set; }
        public string Branch { get; set; }
        public string Passyear { get; set; }
        public string CPI { get; set; }
        public string CGPA { get; set; }
        public string Skill { get; set; }
        public string ExtraSkill { get; set; }
        public string Resume { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual jobseeker_tb jobseeker_tb { get; set; }
    }
}
