//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inbox_tb
    {
        public int ID { get; set; }
        public string Names { get; set; }
        public string Froms { get; set; }
        public string Tos { get; set; }
        public string Messages { get; set; }
        public string Statuss { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
