//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_categorytb
    {
        public job_categorytb()
        {
            this.PostJob_tb = new HashSet<PostJob_tb>();
        }
    
        public int job_cat_id { get; set; }
        public string job_cat_name { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    
        public virtual ICollection<PostJob_tb> PostJob_tb { get; set; }
    }
}
