//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_location
    {
        public Job_location()
        {
            this.PostJob_tb = new HashSet<PostJob_tb>();
        }
    
        public int JobLocation_ID { get; set; }
        public string Location_Name { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual ICollection<PostJob_tb> PostJob_tb { get; set; }
    }
}
