//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Job_DatabaseEntities : DbContext
    {
        public Job_DatabaseEntities()
            : base("name=Job_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin_tb> admin_tb { get; set; }
        public DbSet<ApplyJob_tb> ApplyJob_tb { get; set; }
        public DbSet<Company_tb> Company_tb { get; set; }
        public DbSet<Education_tb> Education_tb { get; set; }
        public DbSet<inbox_tb> inbox_tb { get; set; }
        public DbSet<job_categorytb> job_categorytb { get; set; }
        public DbSet<Job_location> Job_location { get; set; }
        public DbSet<jobseeker_tb> jobseeker_tb { get; set; }
        public DbSet<PostJob_tb> PostJob_tb { get; set; }
    }
}
